version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:password@db:5432/mydatabase?sslmode=disable
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=youraccesskey
      - MINIO_SECRET_KEY=yoursecretkey
      - REDIS_HOST=redis:6379
    depends_on:
      - db
      - minio
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "go run db/migrations/migrate.go && go run main.go"

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000" 
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 

volumes:
  pgdata:
  minio_data:
  redis_data: 